# Generated by Django 5.2.15 on 2026-08-29 11:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0127_operations'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_rooms', to='db.department'),
        ),
        migrations.AddIndex(
            model_name='chatroom',
            index=models.Index(condition=models.Q(('department__isnull', False)), fields=['department', '-created_at'], name='chat_rooms_department_idx'),
        ),
    ]
